version: "2"
services:
    backend:
        image: ziadisafa/spring-boot-jpa-postgresql:0.0.1
        container_name: backend-by-docker-compose
        ports:
            - "8091:8091"
        depends_on:
            - postgres
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testdb
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=8458
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        networks:
            - devops-project-network
          
    # postgres:
    #     image: 'postgres:13.1-alpine'
    #     container_name: postgres
    #     environment:
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=8458
    #         - POSTGRES_DB=testdb
    #     expose:
    #         - 5432
    #     ports:
    #         - "5432:5432"
    #     networks:
    #         - devops-project-network
    #     volumes:
    #         - postgres-data:/var/lib/postgresql/data

    frontend:
        image: ziadisafa/angular-15-crud:1.0.0
        container_name: frontend-by-docker-compose
        ports:
            - "4200:80"
        depends_on:
            - backend
        networks:
            - devops-project-network

# volumes:
#   postgres-data:

networks:
  devops-project-network:
      driver: host
