version: "2"
services:
    backend:
        image: ziadisafa/backend:1.0.0
        container_name: backend
        ports:
            - "8092:8092"
    frontend:
        image: ziadisafa/angular-15-crud:1.0.0
        container_name: frontend
        ports:
            - "4300:80"
        depends_on:
            - backend
