apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  selector:
    matchLabels:
      app: back
  replicas: 0
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: ziadisafa/backend:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
    name: back-svc
spec:
  type: LoadBalancer
  selector:
    app: back
  ports:
    - protocol: "TCP"
      port: 8082 # The port that the service is running on in the cluster
      targetPort: 8082 # The port exposed by the service
      nodePort: 31111