apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  selector:
    matchLabels:
      app: back
  replicas: 1 #à changer
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: ziadisafa/spring-boot-jpa-postgresql:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
    name: back-svc
spec:
  type: LoadBalancer
  selector:
    app: back
  ports:
    - protocol: "TCP"
      port: 8091 # The port that the service is running on in the cluster
      targetPort: 8091 # The port exposed by the service
      nodePort: 31111
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: back-svc
# spec:
#   selector:
#     app: back
#   ports:
#     - protocol: "TCP"
#       port: 8091 # The port that the service is running on in the cluster
#       targetPort: 8091 # The port exposed by the service
#   type: NodePort # type of the service.