apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: ziadisafa/spring-boot-jpa-postgresql:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-boot-k8s-service
# spec:
#   selector:
#     app: spring-boot-k8s 
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 5000
#     targetPort: 8091
#     nodePort: 31110